### ISSUE TITLE
Using form elements

### ISSUE THREAD

**Issue by MazeChaZer** [mdgriffith/elm-ui#102]
I like to use `<form>` elements in combination with an `onSubmit` event handler because this handles enter key presses in all the input fields. So no matter which input is currently focused, the user can always press enter to submit the form. Is there a better way of doing this with the current tools provided by this library or is there a plan to include `<form>` elements? I only saw the `form` function in `Element.Region` which is commented out.

**Comment by Maxim-Filimonov** [comment]
I hacked it together with this code:
```
onKeyLookup : (String -> Maybe msg) -> Attribute msg
onKeyLookup lookup =
    let
        decode code =
            case lookup code of
                Nothing ->
                    D.fail "No key matched"

                Just msg ->
                    D.succeed msg

        isKey =
            D.field "key" D.string
                |> D.andThen decode
    in
    Element.htmlAttribute <| Html.Events.on "keyup" isKey
```
Then on your input element:
```
Input.text
            [ onKeyLookup <|
                \code ->
                    if code == enter then
                        Just <| GenerateTeamNumber

                    else
                        Nothing
            ]
```
I'm a bit confused with onKeyLookup is not exposed from the package though.

**Comment by MazeChaZer** [comment]
I actually went into elm/html and back:

```elm
el []
    (Element.html
        (form [ onSubmit RegistrationSubmit ]
            [ layout []
                (column []
                    [ -- ...
                    ]
                )
            ]
        )
    )
```

**Comment by Maxim-Filimonov** [comment]
@MazeChaZer oh that's near trick. Didn't realise you can use layout inside form. 👍

**Comment by MazeChaZer** [comment]
One additional note: If it's possible to use `form` elements it would be cool if there was a `submitButton` element which produces a `<button type="submit">`. That way, only the `onSubmit` handler for the form has to be specified. Right now I have to specify `onSubmit` on the form and `onPress` on the button with the same `Msg` in a redundant way.

**Comment by MazeChaZer** [comment]
So apparently it's not a great idea to have multiple `layout` elements on your page, that completely broke my styles at one occasion. Also a lot of style definitions seem to be repeatet unecessarily. I now have a better workaround for this problem that doesn't require you to go into html and back: Just put your `form` tag anywhere, give it an `id` and then connect the input fields to it by giving them the form id in the `form` attribute:

```elm
[ Element.html <|
    Html.form [ onSubmit LobbySubmit, id "login-form" ] []
, Input.text
    [ Element.htmlAttribute <| Html.Attributes.form "login-form"
    ]
    { onChange = EmailChanged
    , text = email
    , placeholder = Nothing
    , label = Input.labelAbove [] (text "Email")
    }
]
```

It would be really nice to have a proper solution built into this library to encourage users building UIs with good usability. I hate it when I can't press enter to submit in text input fields and [HTML requires that all input fields belongs a form](https://developer.mozilla.org/de/docs/Web/HTML/Element/Input#attr-form).

**Comment by mdgriffith** [comment]
Hello! 

I've added a [note to the documentation for `Input`](https://github.com/mdgriffith/elm-ui/blob/master/src/Element/Input.elm#L125).

I really do think the solution is to just create an explicit `onEnter` event handler.  It makes things explicit in a way that `form`/`onSubmit` really can't be.  I sketched out [a simple example on Ellie](https://ellie-app.com/5X6jBKtxzdpa1).  In a future release there will likely be more event handlers like this in `Element.Events`.

I also found it interesting when reading about [implicit submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission), that if the form has multiple fields, the implicit submission can be *blocked* if one of those fields is on a certain list.  Really that just makes me want explicitness even more.

I'm going to close this as I think this is resolved in the way that makes sense for this library.  I'm still open to discussions about the accessibility properties of `form` though :)  Maybe that's for a separate issue.

Anyway, thanks for the issue and discussion! ❤️

**Comment by MazeChaZer** [comment]
@mdgriffith Thanks for the explanation! Sounds good to me :+1:

**Comment by francois90** [comment]
Hi @mdgriffith, thanks for this awesome package!

i read your note on the documentation for input and i was wondering if you thought about browser validation. The utility of the <form> tag is not only for implicit submission but also for telling the browser to validate the fields before submission. For example a field with a minimum number of characters will trigger a warning to the user if that constrain is not respected on submission with most browsers.
