### ISSUE TITLE
Cursor appears below placeholder in Form.input

### ISSUE THREAD

**Issue by opsb** [mdgriffith/elm-ui#106]
**Expected behavior**
Placeholder text should appear behind text cursor

**SSCCE**
See https://ellie-app.com/5tMrcSnx4mna1 - note that only some letters overlap the cursor so it's not always obvious. If the first letter of the placeholder text is 't' for instance you can see it (zoom in on the ellie).

![image](https://user-images.githubusercontent.com/46232/57359526-2a3a7880-7178-11e9-9840-43035b16a978.png)

**Versions**
 - OS: OSX
 - Browser chrome
 - Browser Version 74
 - Elm Version 0.19
 - Elm UI Version 1.1.0

**Comment by mdgriffith** [comment]
Fixed in the new version!  Thanks Oliver :)
