### ISSUE TITLE
Create an SSCCE template

### ISSUE THREAD

**Issue by kuon** [mdgriffith/elm-ui#11]
I think it would gain a lot of time for everybody to have an "official" (linked from the README and in the new issue template) way of creating SSCCE for elm ui.

We could create some templates in Ellie.

https://ellie-app.com/3fhCyrxjLw3a1

**Comment by mdgriffith** [comment]
Love that, definitely!

**Comment by mdgriffith** [comment]
I've added a basic bug/unexpected behavior issue template with your ellie, thanks for putting that together.
