### ISSUE TITLE
How to render unescaped text inside Element.text?

### ISSUE THREAD

**Issue by hellgirl** [mdgriffith/elm-ui#110]
Basically I need to render raw html from trusted api. It's a labels which can possibly have some links.

Is there a way to do it? Because looks like when I convert Html.Html msg to Element.msg it escapes.

**Comment by MazeChaZer** [comment]
See http://faq.elm-community.org/#how-can-i-output-literal-html-and-avoid-escaping-of-entities
This isn't something that elm-ui can do so I suggest closing the issue here

**Comment by mdgriffith** [comment]
Ah, yeah Elm doesn't allow raw Html like that.  

You best bet if this is a requirement is to look at [webcomponents](https://www.youtube.com/watch?v=tyFe9Pw6TVE), which might allow you to make it work.  However it's beyond the scope of this library.

Thanks!
