### ISSUE TITLE
Behavior of Element.Keyed.column differs from Element.column.

### ISSUE THREAD

**Issue by mdevlamynck** [mdgriffith/elm-ui#115]
**Welcome!**

The behavior of `Element.Keyed.column` differs from the basic `Element.column`:

1) https://ellie-app.com/5H98VqywMHca1
2) https://ellie-app.com/5H99TXgsjbZa1

**Expected behavior**

I expected the same behavior as the basic `Element.column`:

1) https://ellie-app.com/5H9bdNL4tDta1
2) https://ellie-app.com/5H9fVQCZS3pa1

**Versions**

 - OS: Linux
 - Browser Firefox
 - Browser 67
 - Elm 0.19
 - Elm UI Version 1.1.0

**Comment by mdgriffith** [comment]
Good catch!  Thanks!
