### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by ShalokShalom** [mdgriffith/elm-ui#118]
Hi :hugs: 

I am a newbie in programming and your project looks appealing to me. 
I got the idea to port it to FSharp. What do you think? 

The guys up there say its possible to simply port the code, so long as you are doing no magic.  :sparkles: 

So, now tell me: Do you use magic? :smile:

**Comment by mdgriffith** [comment]
Hello!

Go for it if you want :)  It's a big project but there is no magic, just a lot of CSS and design research.

If you end up porting it, I'd love to see what it looks like in another language.
