### ISSUE TITLE
Update documentation on Responsiveness

### ISSUE THREAD

**Issue by KevinWMatthews** [mdgriffith/elm-ui#119]
Hi all,

Is [this line](https://github.com/mdgriffith/elm-ui/blob/ed45160ce81dc48ce4594774822994e9d79f8506/src/Element.elm#L194) in the Element documentation out of date?

```elm
Task.perform (\size -> WindowResize { width = size.width, height = size.height }) Window.size
```

It refers to `Window.size`, but it looks like [elm-lang/window](https://github.com/elm-lang/window) has moved to `elm/browser`.

I think the appropriate replacement is [Browser.Dom.getViewport](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#getViewport). Something like:

```elm
Task.perform (\viewport -> GetViewport viewport) getViewport
```

That glosses over the need to retrieve and possibly round `viewport.viewport.width` and `viewport.viewport.height`.

Please note that I'm quite new to Elm - I'd appreciate it if someone double-checked my work.

It might also be reasonable to delete this line entirely; the documentation's next line details why it's better to pass the initial width and height in from JavaScript instead of using a Task.

**Comment by mdgriffith** [comment]
Good call.  I added in the link to `getViewport` and just deleted the inline code :)

Docs will be updated in the next release.

Thanks!
