### ISSUE TITLE
Function classifyDevice compares shorter sider in master

### ISSUE THREAD

**Issue by tomstejskal** [mdgriffith/elm-ui#122]
Implementation of `classifyDevice` function in master compares the shorter side of the display against the sizes. But the previous implementation of this function compared the width of the display, which is in landscape mode the longer side. This leads to different results for a typical desktop application.

The change was introduced witch pull request #91. I think this pull request should solve the inconsistent classification of the device in portrait vs landscape mode, but it should retain the semantic of the function and should compare the longer side of the display.

**Comment by mdgriffith** [comment]
Makes sense, thanks!
