### ISSUE TITLE
Border radius is overlapped by inner background

### ISSUE THREAD

**Issue by andys8** [mdgriffith/elm-ui#125]
## Issue

Inner background will overlap and hide outer rounded corners.

![image](https://user-images.githubusercontent.com/13085980/60519360-b03fef00-9ce3-11e9-8c5f-70d475b4378f.png)

https://ellie-app.com/5YnvTgRQG98a1

```elm
module Main exposing (main)

import Element exposing (..)
import Element.Background
import Element.Border
import Html.Attributes


main =
    layout [] <|
        el
            [ Element.Border.rounded 12
            , Element.Border.width 2
            , Element.Border.color (rgb255 0 0 255)
            -- Workaround
            -- , htmlAttribute <| Html.Attributes.style "overflow" "hidden"
            ]
            (el
                [ Element.Background.color (rgb255 255 0 0)
                , padding 10
                ]
                (text "corners missing")
            )
```

## Workaround

```elm
htmlAttribute <| Html.Attributes.style "overflow" "hidden"
```

## Expected behavior

Border radius not hidden or a better way to use `overflow: hidden`.

![image](https://user-images.githubusercontent.com/13085980/60519403-c51c8280-9ce3-11e9-8208-96a0cff9b73a.png)

**Versions**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Chrome
 - Browser Version 75
 - Elm Version 0.19
 - Elm UI Version 1.1.0

**Comment by edkv** [comment]
try `Element.clip`

**Comment by andys8** [comment]
Oh, that's the name the hide the overflow in css. Thanks :)

https://github.com/mdgriffith/elm-ui/blob/df183055635bed46139a2662670e978a0776618a/src/Element.elm#L129
