### ISSUE TITLE
Column of columns attached as a nearby element is broken in 1.1.1

### ISSUE THREAD

**Issue by edkv** [mdgriffith/elm-ui#128]
I just tried 1.1.1 on one of my projects and immediately found this issue: https://ellie-app.com/68Tc3kvqY6Pa1. As you can see nested columns are rendered overlapped. This happens only if you render the whole thing as a nearby element (I tried `inFront` and `behindContent` on `Element.layout` and on a regular `el`). Wrapping nested columns in an `el` helps to avoid the issue.

**Comment by mdgriffith** [comment]
ah, interesting.  Looks like this just happens in Chrome.  
There was a flex-basis change for children of columns which is probably causing this.  I think it's likely an easy fix.

**Comment by mdgriffith** [comment]
ok, it was an easy fix.  I'll do a patch release sometime pretty soon, I want to give a little bit of time in case any other issues show up.

**Comment by edkv** [comment]
great, thank you!

**Comment by andys8** [comment]
I've experienced this issue, too. Thanks for reporting and fixing. I'm going to revert for now.

**Comment by mdgriffith** [comment]
Just released 1.1.2 that fixes this.
