### ISSUE TITLE
multiline unexpectedly one line high

### ISSUE THREAD

**Issue by bburdette** [mdgriffith/elm-ui#130]
https://ellie-app.com/69mHYRcjDDya1

**Expected behavior**

With height (maximum N shrink), the multiline should expand up to N px and then stop.  This does work except in a particular set of circumstances, where it stays only one line high.  I ran across this with:

  - the multiline has height (maximum N shrink)
  - its inside a column
  - the column is inside a row with height fill.

Removing the 'height fill' from the row seems to fix it.

**Comment by bburdette** [comment]
Actually, removing the 'height fill' only makes it intermittent, it doesn't actually fix it.  If I inspect the text editing element in the FF debugger it can make it collapse to one line.  In my app I've found that its ok on first render, then the text controls suddenly collapse.

**Comment by bburdette** [comment]
Was just testing this from master (93ce9a2f1af56fbe8755bd684c258eeb11fc2621) - its working!  

However, if you put a large string (with a lot of newlines) into this same example you get text overflowing the control.  Should I open a separate issue?

**Comment by bburdette** [comment]
![Selection_024](https://user-images.githubusercontent.com/157330/62000690-c6e72500-b09a-11e9-87e2-199905b6f184.jpg)

**Comment by mdgriffith** [comment]
Still working on a few things :)  I have the overflow thing fixed already, but not pushed.

**Comment by mdgriffith** [comment]
OK, just pushed the new changes

**Comment by mdgriffith** [comment]
I think I fixed all the recent regressions, so I'll probably do a release later today

**Comment by bburdette** [comment]
nice!  gave it a quick rebuild here and seems to be behaving well so far.
