### ISSUE TITLE
Input multiline loses focus

### ISSUE THREAD

**Issue by Hodkinson** [mdgriffith/elm-ui#131]
https://ellie-app.com/6dkh45LnX4ka1

When you try to enter more than one character, the input box loses focus.

Seems like a regression in 1.1.1+, as it didn't happen in 1.1.0.

 - Mac
 - Chrome/Safari
 - Elm 0.19
 - Elm UI Version 1.1.3

**Comment by mdgriffith** [comment]
Just released 1.1.4 which fixes this.  Thanks!
