### ISSUE TITLE
`Input.text` in a `row` does not shrink to small width when `fillPortion` is above 1

### ISSUE THREAD

**Issue by chrrasmussen** [mdgriffith/elm-ui#137]
Note that this issue is similar to #134. The difference is `Input.text` has `Element.width (Element.fillPortion 2)`. Since #134 has been fixed (but not released), I have tested this issue on the `master` branch.

Incomplete code example (Complete code example below):
```elm
Element.row
    [ Element.width (Element.px 100) ]
    [ Input.text
        [ Element.width (Element.fillPortion 2) ]
        (...)
    ]
```

When `Input.text` has a `fillPortion` above `1` it does not respect the size of `Element.row`, when the `Element.row`'s width is below `240` pixels. If there are multiple `Input.text` in a `Element.row`, this issue affects all `Input.text` fields that have `fillPortion` above `1`. This issue does not affect `Element.column`.

Complete code example: https://ellie-app.com/6gDpCNnfpFHa1 (Note that Ellie uses elm-ui 1.1.4)

Tested on:
 - OS: macOS 10.14.5
 - Browser: Chrome 76.0, Safari 12.1.1, Firefox 68.0
 - Elm Version: 0.19
 - Elm UI Version: `master` / eaf7041 (This issue was introduced in elm-ui 1.1.1)

**Comment by mdgriffith** [comment]
Thanks for the issue!
