### ISSUE TITLE
`Element.focused []` doesn't change focus styles for input fields

### ISSUE THREAD

**Issue by edkv** [mdgriffith/elm-ui#138]
https://ellie-app.com/6jL2LWM248Ta1

`Element.focused` has no effect for input fields (I tried `text` and `multiline`). I also added a button to demonstrate that it works as expected for it (removes focus styles).

**Expected behavior**
1. Focus styles are removed for `Element.Input.text`.
2. Black background is added to `Element.Input.multiline` on focus.

**Versions**
 - Browser: tested in Chromium and Firefox
 - Elm UI Version: 1.1.4

**Edit:** fixed the link

**Comment by edkv** [comment]
I just tested with 1.1.0 and it works.

**Comment by epfahl** [comment]
I've been struggling with this. Glad I'm not the only one.

I expected `focused []` to remove the shadow/glow for `Input.text` just as it does for `Input.button`. But as @edkv found, this does not seem to be the case.

A workaround is to replace the `layout` node with 

```
layoutWith
        { options =
            [ focusStyle
                { borderColor = Nothing
                , backgroundColor = Nothing
                , shadow = Nothing
                }
            ]
        }
```

This global solution isn't ideal.

It seems reasonable to think that `focused []` should have the same effect on all `Input` types.

**Comment by edkv** [comment]
@mdgriffith thank you!
