### ISSUE TITLE
Browser.Dom.focus compatibility

### ISSUE THREAD

**Issue by mdgriffith** [mdgriffith/elm-ui#15]
Focus and blur currently don't work and require a manual work around by going into JS.

These should work out of the box.

https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom

**Comment by yourSenchou** [comment]
Indeed! I am trying to work around this right now.
If the change isn't so huge, I wouldn't mind helping out!

**Comment by rpc-scandinavia** [comment]
I would guess that the all inputs need a "Maybe Int" which then would be set as the elements id.
I just started to try Elm this week, so I'm not able to implement it.

**Comment by mdgriffith** [comment]
This should be resolved in `1.1.0`  You still have to assign an `id` to the `Input`, but then you can use `Browser.Dom.focus`

**Comment by rpc-scandinavia** [comment]
Thank you, it works.
It took me a while to figure out how, but this lead me to the solution.

https://github.com/mdgriffith/elm-ui/issues/25

https://ellie-app.com/3n6C2f2JGP3a1
