### ISSUE TITLE
Android Chrome, Safari and IE11 seem not rendering properly with 1.1.5 (it was working with 1.1.0)

### ISSUE THREAD

**Issue by lucamug** [mdgriffith/elm-ui#152]
I have a simple demo layout that breaks in elm-ui 1.1.5 but it was kind of working in 1.1.0. Maybe is related to https://github.com/mdgriffith/elm-ui/issues/147 ?

Android Chrome with 1.1.5:
<img width="320" alt="" src="https://user-images.githubusercontent.com/5551094/65395265-7dcdfb80-ddd3-11e9-86cf-0527be9d7438.jpg">

Android Chrome with 1.1.0:
<img width="320" alt="" src="https://user-images.githubusercontent.com/5551094/65395347-85da6b00-ddd4-11e9-9728-a7e8a60105a4.jpg">

Safari with 1.1.5:
<img width="1280" alt="Screen Shot 2019-09-23 at 07 22 42" src="https://user-images.githubusercontent.com/5551094/65395271-87effa00-ddd3-11e9-842a-e55e86d4ec84.png">

Safari with 1.1.0:
<img width="1280" alt="Screen Shot 2019-09-23 at 07 35 10" src="https://user-images.githubusercontent.com/5551094/65395364-b6baa000-ddd4-11e9-945f-ddd34a8f39f8.png">

IE11 with 1.1.5:
![image1](https://user-images.githubusercontent.com/5551094/65215227-c17ce880-dae7-11e9-85e4-c7a72cff33f9.png)

IE11 with 1.1.0:
![image2](https://user-images.githubusercontent.com/5551094/65215228-c2157f00-dae7-11e9-9201-7f384d20fef2.png)

Links:

http://elm-ui-1-1-0.surge.sh/index-empty.html
http://elm-ui-1-1-5.surge.sh/index-empty.html

Code:

https://github.com/lucamug/elm-layout/blob/elm-ui-1-1-5.surge.sh/src/Main.elm

**Comment by HenkPoley** [comment]
Silly suggestion, but did you check at 1.1.3, next 1.1.1 or 1.1.4 ? Each time go half-way to see which version introduced the bug.

**Comment by lucamug** [comment]
I am not sure but I think it was 1.1.1

**Comment by cmditch** [comment]
The culprit can be found here on 1.1.5 https://github.com/mdgriffith/elm-ui/blob/53a2732d9533c242c7690e16506b673af982032a/src/Internal/Style.elm#L1354

**Comment by alexkorban** [comment]
#bug

**Comment by mdgriffith** [comment]
I've added a fix for #147 which I think should address this too:
https://github.com/mdgriffith/elm-ui/commit/22deccc2908de0f98e0dc4cde3709d7dc6363978

I'm trying to find situations where the new fix causes issues.  Let me know if you get a chance to try it out!  (though it's not released yet, so you'd have to vendor the library)

**Comment by lucamug** [comment]
This seems working well now, thank you for the fix! ❤️

**Comment by mdgriffith** [comment]
Wonderful!
