### ISSUE TITLE
Missing Feature: Font Variants

### ISSUE THREAD

**Issue by alexandertrefz** [mdgriffith/elm-ui#16]
There is currently no way to set the [variant](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) of a font.

This is important to make content look right for the specific situation it is in (tabular numbers, proper small caps, slashed 0s etc).

Sidenote: There is also a lower level implementation that allows more features to be used, but is a lot more cryptic called [font-feature-settings](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings)

I would be happy to try my hand on a PR, if you want me to.

**Comment by mdgriffith** [comment]
Just added support for font variants.  Thanks for bringing this up, I was only vaguely aware of font variants but they're pretty cool!

**Comment by alexandertrefz** [comment]
Awesome, thanks!
