### ISSUE TITLE
nesting a `row` in a `paragraph` introduces word-breaks

### ISSUE THREAD

**Issue by jhbrown94** [mdgriffith/elm-ui#165]
Example: https://ellie-app.com/7csJx7sNkKHa1

**Expected behavior**
Using a row to contain stuff inside a paragraph should not introduce word-break points at the end of the row, but it does.  Inspecting the DOM, somehow using the row causes the underlying text element to end up with `display: block` instead of `display: inline`.

**Versions**
 - OS: Linux
 - Browser: Chrome, Firefox
 - Browser Version: Chrome Version 78.0.3904.97 (Official Build) (64-bit), Firefox 70.0.1 (64-bit)
 - Elm Version: 0.19.1 
 - Elm UI Version 1.1.5

**Comment by ebrightfield** [comment]
Any workaround for this?  I'm at a loss right now trying to make an Elm-ui version of the blog example in mdgriffith/elm-markup. Everything I've tried with respect to links as a `Mark.annotation` introduces an undesired line break before and after.

**Comment by jhbrown94** [comment]
I never found a workaround that let me use rows, I think I had to refactor to use lists in place of rows so that I could concat them to have a paragraph contain a single list of non-container elements.

**Comment by alexkorban** [comment]
#bug #has-ellie
