### ISSUE TITLE
text input label not baseline aligned

### ISSUE THREAD

**Issue by jerith666** [mdgriffith/elm-ui#172]
This example ([see it in Ellie](https://ellie-app.com/7xtZYhXjMXBa1)) illustrates that a "dissociated" label lines up correctly, but an "associated" label does not:

    main =
        Element.layout [] <|
            Element.column []
                [ Element.row []
                    [ Element.text "dissociated label"
                    , Input.text []
                        { text = "input"
                        , label = Input.labelHidden "hidden"
                        , onChange = \_ -> Msg
                        , placeholder = Nothing
                        }
                    ]
                , Element.row []
                    [ Input.text []
                        { text = "input"
                        , label = Input.labelLeft [] <| Element.text "associated label"
                        , onChange = \_ -> Msg
                        , placeholder = Nothing
                        }
                    ]
                ]

**Expected behavior**
Labels created via `Element.Input.label*` functions should baseline align with the `Element.Input.text` that they're linked to.

**Versions**
 - OS: Linux
 - Browser: Google Chrome | 79.0.3945.79 (Official Build) (64-bit) Revision 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
 - Elm Version: 0.19.1
 - Elm UI Version: 1.1.5

**Comment by alexkorban** [comment]
#bug #has-ellie
