### ISSUE TITLE
z-index issue with `below` `above` `onRight` `onLeft`

### ISSUE THREAD

**Issue by agj** [mdgriffith/elm-ui#175]
Elements placed as in the title, unexpectedly appear on top of the element that's `inFront` of the `layout`. Here's an example:

https://ellie-app.com/7JTBZXb7wZXa1

I found issue #22 to be identical but with `inFront`, and that one seems to have been fixed.

**Expected behavior**
Element that's `inFront` at `layout` level should be on top of other relatively positioned elements in the page.

**Versions**

- OS: macOS
- Browser: Firefox
- Browser Version: 71.0
- Elm Version: 0.19.1
- Elm UI Version: 1.1.5

**Comment by alexkorban** [comment]
#bug #has-ellie
