### ISSUE TITLE
Font.alignRight and Font.center has no effect on Element.Input.text

### ISSUE THREAD

**Issue by daniels** [mdgriffith/elm-ui#188]
When adding `Font.alignRight` or `Font.center` to the attribute list passed to `Element.Input.text` I expect the value to be aligned accordingly. Instead, the attribute is ignored and the value is always aligned to the left.

See this Ellie for a comparison with an Element.el with the same attributes: https://ellie-app.com/8pcyfdKmfkDa1

**Versions**
 - OS: MacOS 10.13.6
 - Browser: Chrome/Safari
 - Browser Version: 80.0.3987.149/13.0.4
 - Elm Version: 0.19, 0.19.1 (Ellie)
 - Elm UI Version: 1.1.5

**Comment by daniels** [comment]
Oh, and of course a workaround is to add:

```
Element.htmlAttribute (Html.Attributes.style "text-align" "right")
```

**Comment by alexkorban** [comment]
#bug #has-ellie

**Comment by mdgriffith** [comment]
Fixed in https://github.com/mdgriffith/elm-ui/commit/4d7e114ac16fdc6f631fb2a119c6a2e904d128b6

Thanks!
