### ISSUE TITLE
Port to Purescript

### ISSUE THREAD

**Issue by ajnsit** [mdgriffith/elm-ui#189]
This is not a real issue. I just wanted to thank all the contributors for a really great lib!

I don't use Elm myself, but I love the idea of this library, so I have started work on a Purescript port! https://github.com/purescript-concur/purescript-concur-ui.

It already works for some things, for example - A simple [layout example](https://purescript-concur.github.io/purescript-concur-ui/) ([Source](https://github.com/purescript-concur/purescript-concur-ui/blob/master/src/Main.purs)).

**Comment by mdgriffith** [comment]
Very cool!  I've added it to my notes of projects to watch :D 

I'm going to close this issue, but thanks for letting me know
