### ISSUE TITLE
el [ clip ] inside a fixed-width column rendered with 0px height in Chrome & Firefox

### ISSUE THREAD

**Issue by alexkorban** [mdgriffith/elm-ui#191]
If an `el [ clip ]` is placed inside a fixed-width column which is inside a layout with `[ width fill, height fill ]`, then the element is rendered with 0px height in Chrome: 

    layout [ width fill, height fill ] <|
        column [ width <| px 300 ] 
            [ el [ clip ] <| text "The quick brown fox" ]

Ellie: https://ellie-app.com/8vTsZfn4Qvva1

In Firefox, the element is initially rendered correctly, but is resized to 0px height on viewport resize. In Safari, the element is displayed correctly. 

The above seems to be the minimal reproduction:
- Removing attributes from `layout` or from `column` or from `el` makes the issue disappear. 
- Replacing `column [ width <| px 300 ]` with `column [ width fill ]` makes the issue disappear.
- Replacing `column` with `el` also makes the issue disappear. 

Adding `htmlAttribute <| Attr.style "flex-basis" "auto"` to clipped `el` is a workaround.

**Expected behavior**
Element doesn't get resized to 0px height. 

**Versions**
 - OS: mac OS
 - Browser: Firefox, Chrome
 - Browser Version:  Firefox 74.0.1, Chrome 80.0
 - Elm Version: 0.19.1
 - Elm UI Version: 1.1.5

**Comment by alexkorban** [comment]
#bug #has-ellie

**Comment by mdgriffith** [comment]
I believe this is resolved with this commit!
https://github.com/mdgriffith/elm-ui/commit/22deccc2908de0f98e0dc4cde3709d7dc6363978
