### ISSUE TITLE
Div inside goes out of borders

### ISSUE THREAD

**Issue by CharlonTank** [mdgriffith/elm-ui#196]
**Welcome!**
Here, this el fills the column width and height and have background color
Is it normal that it goes out of bound in terms of borders?
https://ellie-app.com/8Cqc3r46tsWa1

**Expected behavior**
Setting background of a div inside a rounded div would not go over the borders

**Versions**
 - OS: Max OS 10.15.4
 - Browser : Chrome
 - Browser Version : Version 80.0.3987.149 (Official Build) (64-bit)
 - Elm Version : 0.19.1
 - Elm UI Version : 1.1.5

**Comment by alexkorban** [comment]
Workaround: add `clip` to your first example in the Ellie, then the `el` inside doesn't spill out anymore. 

I think that behaviour is kind of expected - content overflows by default, if not clipped. For example, long text will overflow your second element with a border as well.

**Comment by alexkorban** [comment]
#unexpected

**Comment by CharlonTank** [comment]
Oh the use of clip is what I was searching, thank you so much <3
