### ISSUE TITLE
`focused` style applied to an element when any element with a lower tab index is focused

### ISSUE THREAD

**Issue by alexkorban** [mdgriffith/elm-ui#198]
When I add a `focused` attribute, the styles therein are applied not only when the element is focused, but also when any element with a _lower_ tab index is focused. This behaviour is not browser-specific. 

To reproduce, tab through to the buttons in the Ellie below. As soon as the first button has focus, the _third_ button (which is the only one with a `focused` attribute) is highlighted as well. 

Ellie: https://ellie-app.com/8DwT5tXGJcpa1

I narrowed down the reason for this behaviour to this CSS selector: 
`.s:focus ~ .fc-250-50-50-255-fs:not(.focus)` 

Disabling it produces the correct focus behaviour. 

I can see that it's generated as part of the focus style in `Internal.Model.renderStyle` but I can't understand why. 

**Expected behavior**

The `focused` style should only be applied when the given element has focus.

**Versions**
 - OS: mac OS 10.14.6
 - Browser: Safari, Firefox, Chrome
 - Browser Version: Safari 13.0.1, Firefox 75.0, Chrome 80.0.3987.163 
 - Elm Version: 0.19.1
 - Elm UI Version: 1.1.5

**Comment by miniBill** [comment]
Related to #97 ?

**Comment by alexkorban** [comment]
Not sure, that looks like a different issue to me.
