### ISSUE TITLE
Rounding error on padding of wrappedRow

### ISSUE THREAD

**Issue by mdevlamynck** [mdgriffith/elm-ui#199]
**Welcome!**
When using both `spacing` and `padding` on a `wrappedRow` and when the `spacing / 2 < padding`, elm-ui has to add some padding on the parent div (more precisely `padding - (spacing / 2)` of padding). It seems it instead adds `padding - (spacing // 2)` which is too big by 0.5.

If I'm not mistaken the rounding error comes from https://github.com/mdgriffith/elm-ui/blob/master/src/Element.elm#L650.

 It works as expected with a `row`.

Example with rounding error : https://ellie-app.com/8GyYtXcqDSQa1
Example that works as expected : https://ellie-app.com/8Gz2gwyMXvva1 (since the padding is even the rounding error ends up not being an issue)

**Expected behavior**
The padding on the wrappedRow should not be rounded.

**Versions**
 - OS: Linux
 - Browser Firefox (v75.0), Chromium (v81.0)
 - Elm Version 0.19.1
 - Elm UI Version 1.1.5

**Comment by alexkorban** [comment]
#has-ellie #bug
