### ISSUE TITLE
`height fill` on Element.layout

### ISSUE THREAD

**Issue by danielmartinprieto** [mdgriffith/elm-ui#20]
Hi! Newbie here. I was wondering how can I get the height of the layout to fill the entire space of the body. This works in Ellie, of course, but how can I get the same behaviour for the root element of my site?
```
main =
    Element.layout [ height fill ] -- this only doesn't work :(
        myRowOfStuff
```
Thanks!

**Comment by lsunsi** [comment]
@danielmartinprieto Isn't layout already full width and height? I was under the impression it was. :(
If it is, maybe your just not propagating the full height to your inner elements.

Also, maybe the way you initialise the program makes a difference here, (element, document, etc). But this is just guesswork.

**Comment by danielmartinprieto** [comment]
Just the line from above in a new Elm app (using create-elm-app) doesn’t work for me. There is full width but not height. I’m using `Browser.program`, btw. Isn’t that your experience as well? It works for me in Ellie, but I think that makes sense because your _main_ in Ellie is a subview if the whole app.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlmightyFloppyFish** [comment]
Element.layout starts with height fill, just try 
`Element.layout [ Background.color ( rgb 0.5 0.5 0.5 )] (myRowOfStuff)`

**Comment by danielmartinprieto** [comment]
That's not what I'm experiencing, unfortunately. In a fresh app using `create-elm-app`, I just copied the example from the readme of this repo and used it as the view of my program. It doesn't fill the whole height of the screen, only the space that the row takes.

```elm
module Main exposing (..)

import Browser
import Html exposing (Html, text, div, h1, img)
import Element exposing (Element, el, text, row, alignRight, fill, width, rgb255, spacing, centerY, padding)
import Element.Background as Background
import Element.Border as Border
import Element.Font as Font


---- MODEL ----


type alias Model =
    {}


init : ( Model, Cmd Msg )
init =
    ( {}, Cmd.none )



---- UPDATE ----


type Msg
    = NoOp


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    ( model, Cmd.none )



---- VIEW ----


view : Model -> Html Msg
view model =
    Element.layout [ Background.color (rgb255 0 0 0) ]
        myRowOfStuff


myRowOfStuff : Element msg
myRowOfStuff =
    row [ width fill, centerY, spacing 30 ]
        [ myElement
        , myElement
        , el [ alignRight ] myElement
        ]


myElement : Element msg
myElement =
    el
        [ Background.color (rgb255 240 0 245)
        , Font.color (rgb255 255 255 255)
        , Border.rounded 3
        , padding 30
        ]
        (text "stylish!")



---- PROGRAM ----


main : Program () Model Msg
main =
    Browser.element
        { view = view
        , init = \_ -> init
        , update = update
        , subscriptions = always Sub.none
        }

```

**Comment by AlmightyFloppyFish** [comment]
This is what i get from that code, it's not the same for you? 

If not you might wanna double check that you're using elm 0.19, or maybe try another browser?

![image](https://user-images.githubusercontent.com/29797280/45898264-0254fb00-bdc9-11e8-8300-1e1af0c60b65.png)

**Comment by danielmartinprieto** [comment]
So weird, I can confirm that I'm using Elm 0.19, and I've tried in Safari, Chrome and Firefox in macOS High Sierra. This is what I get, see how the height is only the space the row is taken and therefore is not centered in the screen.

![image](https://user-images.githubusercontent.com/2881251/45916418-33373d80-be66-11e8-8fc5-34d18bc8a0a6.png)

As a boilerplate of the app I used https://github.com/halfzebra/create-elm-app 13 days ago.

**Comment by danielmartinprieto** [comment]
Mmm, you’re right. Creating the project with `elm init` makes it work as expected. I’ve seen there is some basic css generated with `create-elm-app`, but removing it doesn’t change anything, so I’m wondering what’s the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlmightyFloppyFish** [comment]
Then something from create-elm-app must be overwriting, it does add some JS files as well so they could also be causing issues. Since this isn't an issue with elm-ui maybe close the issue?

**Comment by danielmartinprieto** [comment]
Yes! Thanks for your help.
