### ISSUE TITLE
column does not keep ratio when using 'height fillPortion' on children

### ISSUE THREAD

**Issue by marmutro** [mdgriffith/elm-ui#203]
https://ellie-app.com/8JHZjCfFjHVa1

**Expected behavior**
The height of column elements should be kept at a given ratio by using fillPortion. But when the height one of the elements increases, the height of the other shrinks.
Setting the CSS property flex-basis to 0 seems to fix this bug.

**Versions**
 - Browser: Chrome  81.0.4044.113 and Firefox 68.7.0

**Comment by rlefevre** [comment]
Here is the Ellie without the `flex-basis: 0` work-around, to show the actual issue:
https://ellie-app.com/8JP9V3LZzQ7a1

#bug #has-ellie
