### ISSUE TITLE
1.1.6 breaks images with no width, height within rows

### ISSUE THREAD

**Issue by shaydon** [mdgriffith/elm-ui#228]
[Ellie](https://ellie-app.com/926dBdbMmpna1).

An image without width or height specified is invisible (displays with width / height of zero) when its a child of a row element.

This appears to be a consequence of commit fe2b14b which sets a max-width/height on images.

**Expected behavior**
The image should display inline at its "natural" size, as it did in elm-ui 1.1.5.

**Versions**
 - OS: ChromeOS
 - Browser: Chrome
 - Browser Version: 83
 - Elm Version: 0.19.1
 - Elm UI Version: 1.1.6

**Comment by mdgriffith** [comment]
Thanks for the issue and sorry about the regression!

I just released 1.1.7 which should have this fixed.
