### ISSUE TITLE
Dramatic width and clipX behavior change from 1.1.5

### ISSUE THREAD

**Issue by bawolk** [mdgriffith/elm-ui#232]
I have a working card game.  Each hand is displayed in a row, with the cards overlapping.  The basic card image is 119 px wide and 166 px.  In elm-ui-1.1.5, the overlap was accomplished using [width (px 50), clipX] as attributes.  The basic code is in this ellie:
https://ellie-app.com/94rBbHwLx9Va1
If you run this code under 1.1.6, only the queen displays and the ace is not shown.  Also the queen is smaller than it should be, seemingly shrunk proportionally.

Expected behavior:  In 1.1.5 the card image would not be shrunk, but the only the first 50 pixels of the queen would be visible, and a full image of the ace would be next to it.

**Versions**
 - OS: Ubuntu 18.4
 - Browser Firefox
 - Browser Version 76
 - Elm Version 0.19.1
 - Elm UI Version 1.1.6

**Comment by mdgriffith** [comment]
Thanks for the issue and sorry about the regression!

I just released 1.1.7 which should have this fixed.
