### ISSUE TITLE
Input.text (and variants like Input.search)

### ISSUE THREAD

**Issue by kephas** [mdgriffith/elm-ui#249]
**Summary**

As visible in https://ellie-app.com/9yJ3wB9Trgna1, the input loses focus when
- the input's placeholder changes from `Just something` to `Nothing`
- the input's placeholder changes from `Nothing` to `Just something`

This does NOT happen when the changes is between two `Just` values.

I would guess this is because the input with a placeholder is rendered as two nested `<div>` but the one without placeholder is rendered with only one `<div>` around the `<input>`.

Problem verified with 
- `Input.text`
- `Input.username`
- `Input.search`
- `Input.newPassword`

**Expected behavior**
I expect the input I'm typing in the keep focus after I type the first character.

**Versions**
verified on
- Firefox Quantum 68.7.0esr
- Chromium 81.0.4044.92

**Comment by mdgriffith** [comment]
Hello!

The placeholder will automatically switch off when there's content, you don't need to change it yourself.

https://ellie-app.com/9yJRvPcjMRFa1

Probably should be clearer in the docs!

**Comment by kephas** [comment]
Can this be reopened for the documentation?
