### ISSUE TITLE
Regression 1.1.8 on Safari only, scrollbar does not confine element

### ISSUE THREAD

**Issue by perty** [mdgriffith/elm-ui#265]
Using @alexkorban chat example on Safari stops working as intended when switching from 1.1.7 to 1.1.8.

The messages in the chat are supposed to be scrolled while the input footer remains. However, on Safari, the chat messages just overflows and pushes the footer down.

See Ellie: https://ellie-app.com/bDZPLdTmV84a1 .  Unfortunately, I could not make Ellie pick another version of elm-ui than the latest.

**Expected behavior**
The footer remains while the messages are scrolled.

**Versions**
 - OS: MacOs
 - Browser Safari  
 - Browser Version  14.0 (15610.1.28.1.9, 15610)
 - Elm Version 0.19.1
 - Elm UI Version 1.1.8

**Comment by globodesk** [comment]
1.1.8 requires adding `height <| minimum 0 fill` to the inner column to stop it overflowing. It's actually a simpler fix than in prior versions, but it's still not obvious.

**Comment by alexkorban** [comment]
1.1.8 requires adding height <| minimum 0 fill to the inner column to stop it overflowing. It's actually a simpler fix than in prior versions, but it's still not obvious.

**Comment by perty** [comment]
Thanks @alexkorban - I could never have had  come up with that myself.  As you say, not obvious. I mean, fill at least zero amount? 

You rock, Alex.

**Comment by perty** [comment]
I am closing this as it apparently is fixable.
