### ISSUE TITLE
Autocomplete missing on email input

### ISSUE THREAD

**Issue by MartinSStewart** [mdgriffith/elm-ui#266]
The autocomplete behavior is missing on `Element.Input.email`. When clicking on an email field the expected behavior is for the browser to offer to fill it in with my email but this doesn't happen on elm-ui's email field. The work around for now is to add `Element.htmlAttributes <| Html.Attributes.attribute "autocomplete" "email"`.

**Comment by pravdomil** [comment]
It looks that is resolved?

https://github.com/mdgriffith/elm-ui/blob/7919c5e4f43741fc2d9b98a60fdd354fdb31a997/src/Element/Input.elm#L1560

**Comment by MartinSStewart** [comment]
It looks like it. I might have mistakenly used an outdated version of elm-ui when I created this issue.
