### ISSUE TITLE
Cannot change text input contents

### ISSUE THREAD

**Issue by hololeap** [mdgriffith/elm-ui#271]
I cannot change the contents of a text input box after it has been rendered.

Example: https://ellie-app.com/cjJVPmM7zBBa1

It has the same problem if you change the `text` field:
```
                { onChange = Change
                , text = ""
                , placeholder = Nothing
                , label = labelAbove [] (Element.text "Text to reverse")
                }
```

This is frustrating because I was excited to try this library, but this basic functionality seems totally broken.

**Versions**
elm-0.19.1
elm-ui-1.1.8

Tested in:
- Brave Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) unknown (64-bit) (Linux)
- Edge 88.0.705.63 (Windows 10)

**Comment by bburdette** [comment]
Here, try this:

https://ellie-app.com/cjKXPxrZ2Pwa1

Stick with it, elm-ui is awesome : )

**Comment by hololeap** [comment]
@bburdette Wow, thanks! I didn't expect the fix to be so simple. That's going to save me a huge headache.

**Comment by bburdette** [comment]
The way it works is typical for elm UI things in general (html, elm-ui, or other) - your "view" fn takes your model data and builds the UI with it, seemingly from scratch every time.  Initial values are not kept in UI elements, but in the model data.  

For more rapid response on these kinds of issues, I recommend the elm slack:
https://elmlang.herokuapp.com/

There are a lot of channels on there, #beginners is a great place to check out, as well as #elm-ui.

**Comment by hololeap** [comment]
@bburdette Thanks again. I was asking on #elm IRC in Freenode and wasn't getting any responses.
