### ISSUE TITLE
[Feature Request] Css Transitions

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [mdgriffith/elm-ui#29]
They're definitely a must have for modern mobile development when making sliding navigation menus or animated burger icons.

**Comment by AlmightyFloppyFish** [comment]
In my opinion this should be the nr1 priority for this project right now. Every single modern website these days uses transitions, so by definition the lack of it prevents elm-ui from making any modern looking website.

**Comment by mdgriffith** [comment]
Nothing is preventing you from using CSS transitions via either inline styles or normal style classes using `htmlAttribute`.  There should be no blocker here.

I do have an animation solution that I'm working on, but it will probably still be a bit of time before it's ready.
