### ISSUE TITLE
Rename Border.width to Border.thickness

### ISSUE THREAD

**Issue by dullbananas** [mdgriffith/elm-ui#298]
Element.Border.width and Element.width are easy to mix up

**Comment by Yagger** [comment]
Use absolute names, it makes your code more readable and is good practice in general, and eliminates any naming conflicts.

import Element as E
import Element.Border as Br
import Element.Background as Bg
import Element.Font as Font

E.width
Br.width
Br.color
Bg.color
Font.color

Naming consistency across modules is convenient.
