### ISSUE TITLE
Make text unselectable?

### ISSUE THREAD

**Issue by mitchellwrosen** [mdgriffith/elm-ui#336]
Hi, is it possible to make text unselectable using this library?

From a [cursory google search](https://stackoverflow.com/questions/69430/is-there-a-way-to-make-text-unselectable-on-an-html-page) it looks like `user-select: none` CSS is the trick. However, I couldn't figure out how to accomplish that with the external API.

Thanks!

**Comment by Viir** [comment]
Yes, you can disable selection with this attribute:

```Elm
Element.htmlAttribute (Html.Attributes.style "user-select" "none")
```

**Comment by mitchellwrosen** [comment]
Nice, I missed that. Thanks.
