### ISSUE TITLE
Missing old `screen` function

### ISSUE THREAD

**Issue by dmattia** [mdgriffith/elm-ui#37]
I believe it is impossible without the old `screen` function to create a fixed overlay over a page that extends beyond the viewport.

Ex: say you are making a news feed with a scrollable list of posts. When a user clicks on an image, you want to create a light box modal displaying a larger view of that image.

Afaik, your options are either to
1) `fill height` above the posts element, which will create a gigantic overlay with a probably incorrect center
2) subscribe to the height of the screen, store that value in your model, and set the height of the modal to that value. This is also problematic, as the user can scroll around the modal.

Proposed solution: bring back the `screen` function

**Comment by mdgriffith** [comment]
Hello!

If you use `inFront` in the `Element.layout` attributes, then it'll be `position:fixed` just like `screen`.

I realize the discoverability of that is pretty low, so my plan is to have a comprehensive guide soon that'll go over common situations like this.

Thanks for the issue!

**Comment by JDemler** [comment]
So if there is some function somewhere that want's to open a modal it has to backpropagate the element to the layout function?

I tried to hack it with `Element.html <| Element.layout [ Element.inFront inner ] Element.none`.
That worked visually but interaction with element in `inner` was not possible (input fields).

**Comment by mdgriffith** [comment]
This is based on the idea that in Elm flat models tend to be easier to work with than overly nested ones.

So, there should be no back-propagation, just keep modal logic as a top-level concern in your model.

I will mention that that hack can break due to CSS weirdness.  `position: fixed` is positioned based on the viewport, or any ancestor that has `tranform`, `perspective` or `filter` set on it.

https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed

**Comment by JDemler** [comment]
Thanks for the clarification. 
I'm trying to use `elm-ui` in a SPA which seem to be inherently nested. At least one level.

Look at the "official" SPA example: https://github.com/rtfeldman/elm-spa-example/blob/master/src/Page.elm#L42

The html of the header and the page and the footer are combined in the view function.
There seem to be some solutions to pass the modal to that view function, which would probably call `Element.layout` if written with `elm-ui`, but none seem as simple and straightforward as calling `screen` in the pages view function. Hm....

The way to go with the current way to build modals seems to be to extend the return type of the `view` function for every page by a `modal: Maybe (Element msg)`.

**Comment by mdgriffith** [comment]
Yeah, hmm 🤔  

So, one question I have is how many different modals are needed?

I know login/registration is common.  For that I actually make login status a top level issue(like it is in the SPA example as the session data). Then the main view function knows if a page should be protected by login and can display the modal when it needs to.

**Comment by JDemler** [comment]
And when the user presses the `Sign In` button in the header and it should be handled by a modal?

The only possible way, I can think of, to achieve that, besides returning a modal from the `Header.view` is to (miss)use routes. (e.g. add the fragment 'sign_in'). 
Then the main module can detect it and open to modal. But that seems ugly and hacky.

Just FYI, I currently use this:
``` elm
modal : Element msg -> Element msg
modal inner =
    el
        [ Background.color <| rgba 0.0 0.0 0.0 0.6
        , Element.htmlAttribute <| Attributes.style "position" "fixed"
        , Element.htmlAttribute <| Attributes.style "z-index" "1000"
        , Element.htmlAttribute <| Attributes.style "top" "0"
        , Element.htmlAttribute <| Attributes.style "left" "0"
        , Element.htmlAttribute <| Attributes.style "width" "100%"
        , Element.htmlAttribute <| Attributes.style "height" "100%"
        ]
    <| inner
```

Of course this is a hack around elm-ui and probably not at all what you intended to happen, but it gets the work done.
