### ISSUE TITLE
Extra space added in paragraph sequence

### ISSUE THREAD

**Issue by Augustin82** [mdgriffith/elm-ui#39]
Here is an Ellie reproducing the issue: https://ellie-app.com/3vqbQn54jM3a1
As you see, there is a space before `HOWEVER` that should not be there.

This is using **Elm 0.19** and **Elm-UI 1.0.0** on both **Firefox 62.0** and **Chrome 69.0.3497.100** for **Ubuntu 18.04**.

**Comment by mdgriffith** [comment]
Thanks Augustin!  This should be fixed in `1.1.0`.
