### ISSUE TITLE
Border shadow doesn't display when offsets are float values

### ISSUE THREAD

**Issue by yourSenchou** [mdgriffith/elm-ui#44]
When the border shadow offset property is a float that's value has any number after the "." that isn't zero, it doesn't display the shadow at all. 

[Example](https://ellie-app.com/3xkQyfCTLrJa1)

**Expected behavior**
The expected behavior is for the shadow to display when a float value is given for the offset

**Versions**
 - OS: [macOS Mojave]
 - Browser [chrome]
 - Browser Version [Version 69.0.3497.100 (Official Build) (64-bit)]
 - Elm Version [0.19]
 - Elm UI Version [1.0.0]

**Comment by ldesgoui** [comment]
Produced class name is "box-inset0.5px0px3px1px0-0-0-77", which is understood as two classes, "box-inset0" and "5px0px3px1px0-0-0-77" by the CSS engine
