### ISSUE TITLE
prop escape hatch?

### ISSUE THREAD

**Issue by bstro** [mdgriffith/elm-ui#46]
Really missing the `prop` function from style-elements. Has this been replaced by anything else? Very many things become impossible without it!

**Comment by AlmightyFloppyFish** [comment]
The jquery function? I really can't see how things would be impossible without it, I've never even seen it before.

**Comment by mdgriffith** [comment]
You can do inline styles using `Element.htmlAttribute (Html.style "font-size" "1.2rem")`.

What do you usually do for fluid typography? Do you mean using `em/rem` or are you talking about scaling the font with the window size?

**Comment by bstro** [comment]
I was referring to fluid typography using `em/rem` as described [here](https://css-tricks.com/snippets/css/fluid-typography/) – but I'm thinking I might be able to accomplish something very similar by subscribing to the window dimensions and recalculating font sizes that way.

**Comment by mdgriffith** [comment]
Ah, ok cool.  Yeah, that's the way to go!
