### ISSUE TITLE
fillPortion and image not playing well together

### ISSUE THREAD

**Issue by bburdette** [mdgriffith/elm-ui#48]
**Example**
I've got an example here where 3 elements are sized using fillPortion 1, the middle element being an image.  It works ok!  But if you change the image fillportion to 2, the image displays at its full resolution.

https://ellie-app.com/3zztzKkg8X4a1

**Expected behavior**
I expected the image to still be in between the two other elements, but just a little larger - taking up 1/2 the width of the window rather than 1/3.  

**Versions**
 - OS: nixos
 - Browser: firefox, chrome
 - Browser Version: ff62.0.03, chromium Version 69.0.3497.81 (Developer Build) (64-bit)
 - Elm Version 0.19.0
 - Elm UI Version 1.1.0

**Comment by alexkorban** [comment]
No longer happens with elm-ui 1.1.5.
