### ISSUE TITLE
The text in a multiline input doesn't always match the value set in its `text` field. 

### ISSUE THREAD

**Issue by dela3499** [mdgriffith/elm-ui#5]
The `text` option of a multiline input has unintuitive behavior. It can set the initial value of the input, but changing it doesn't update the input text. I use Element.Keyed as in the case below to update multiline input text. (Changing the key creates a new element with the provided `text` value.)

In this example, there are two inputs, each of which has its `text` field set by the same value - the model's `text` field. The left input is a `multiline` and the right is a `multiline` wrapped in a keyed element. 

I'd expect the displayed text in each input to match it's `text` field, but an input only updates as long as it hasn't yet been typed into.

If you type into each input, then click the `Update text and key` button, the left input will not update, and the right input will update, since it is keyed and the key has just changed. 

![multiline](https://user-images.githubusercontent.com/5673550/44937078-25960880-ad3d-11e8-9446-bccc88319dfd.png)

```elm
module Main exposing (main)

import Browser
import Debug
import Element exposing (..)
import Element.Background as Background
import Element.Input as Input
import Element.Keyed as Keyed


main =
    Browser.sandbox
        { init = init
        , view = view
        , update = update
        }


init =
    { text = "initial text"
    , key = "initial key"
    }


type Msg
    = SetText String
    | UpdateInput


update msg model =
    case msg of
        SetText string ->
            { model | text = string }

        UpdateInput ->
            { model
                | text = "updated text"
                , key = "updated key"
            }


options string =
    { onChange = SetText
    , text = string
    , placeholder = Just (Input.placeholder [] (text ""))
    , label = Input.labelAbove [] none
    , spellcheck = False
    }


view model =
    Element.layout [ width fill, height fill ] <|
        column [ width fill ]
            [ row [ width fill, height fill ]
                [ el [ width fill ]
                    (Input.multiline [] (options model.text))
                , Keyed.el [ width fill ]
                    ( model.key, Input.multiline [] (options model.text) )
                ]
            , Input.button
                [ width fill
                , paddingXY 10 10
                , Background.color (rgba 0 0 0 0.1)
                ]
                { onPress = Just UpdateInput
                , label = text "Update text and key"
                }
            , el [ centerX, padding 50 ] (text (Debug.toString model))
            ]

```

**Comment by mdgriffith** [comment]
Interesting!

I'm wondering if this is really behavior due to Elm itself versus this library.

I've put your code into an [ellie](https://ellie-app.com/3cLRk4DvXnRa1).

The super weird part, is if you open up the inspector and take a look at the `textarea` elements when they get out of sync...they're actually showing the same internal text, it's just not rendering. 🤔   At least in firefox.

**Comment by mdgriffith** [comment]
Ok, yeah this is something on the `elm/html` level.  If I switch to an `Input.text`, then I don't see them getting out of sync:

https://ellie-app.com/3cLXQcSYMcqa1

**Comment by tomstejskal** [comment]
I've found this issue in elm/html:
https://github.com/elm/html/issues/55

There is also mentioned a workaround in a comment in another issue:
https://github.com/evancz/elm-html/pull/81#issuecomment-309553890

**Comment by ymtszw** [comment]
Just logging that this still is an issue with recent elm/virtual-dom@1.0.2.
Also, `Keyed` workaround suggested in https://github.com/evancz/elm-html/pull/81#issuecomment-309553890 has a flaw that newly generated `textarea` DOM will lose focus (since it is a different DOM than the previous one?), makes it almost unusable.

**Comment by perty** [comment]
Here is an ellie where I compare the behaviour of elm-ui and elm/html. [https://ellie-app.com/52FxBzLnVFDa1](https://ellie-app.com/52FxBzLnVFDa1)

The fields are Html.input, Html.textarea, Input.text and Input.multiline. All except the last behaves as expected. When the model changes, so do they. The last one, multiline, does also change unless you have typed anything. Then what you have typed, gets stuck.

I expected the multiline to behave more like the others.

**Comment by perty** [comment]
Looking into this with developer tools, I can see a difference between Html.textarea and Input.multiline. When I change the text, Html.textarea still is `<textarea></textarea>` while Input.multiline becomes `<textarea>Entered text</textarea>`.

It is beyond me how the textarea element works in the browser. I thought what elm-ui does was correct.

**Comment by perty** [comment]
Ok, some more digging. When I change the model, Html.textarea changes the `value` attribute of the `<textarea>`. Input.multiline does not, it changes what is between the tags, instead.

I found this by setting id on the textareas and looking in the console.

**Comment by bburdette** [comment]
mdgriffith suggested trying the value attrib on Slack, so I gave it a try.  So far this is working well, and no key counters to keep track of:

```
import Html.Attributes as HA
import Json.Encode as JE

workAroundMultiLine :
    List (Attribute msg)
    ->
        { onChange : String -> msg
        , text : String
        , placeholder : Maybe (Input.Placeholder msg)
        , label : Input.Label msg
        , spellcheck : Bool
        }
    -> Element msg
workAroundMultiLine attribs mlspec =
    Input.multiline (htmlAttribute (HA.property "value" (JE.string mlspec.text)) :: attribs)
        mlspec

```

**Comment by perty** [comment]
Thank you @bburdette . My solution was to use Html.textarea instead.

                Element.html
                    (Html.textarea
                        [ Html.Attributes.value model.currentMessage
                        , Html.Events.onInput MessageUpdate
                        , Html.Attributes.rows (rowCount model.currentMessage)
                        ]
                        []
                    )

Where `rowCount` is a function that estimates the needed number of rows.

**Comment by andys8** [comment]
@mdgriffith I can confirm the fix by @bburdette

**Comment by bburdette** [comment]
I added a PR.  Haven't run the full test suite on it yet, that's giving me problems.  But it does seem to fix the exampes here, like this one:  https://ellie-app.com/52FxBzLnVFDa1
