### ISSUE TITLE
Input.Slider is rendered in front of InFront elements

### ISSUE THREAD

**Issue by sturgman** [mdgriffith/elm-ui#55]
This is an issue reported by Leif Battermann in the Slack channel. SSCCE:

https://ellie-app.com/3DytzyCwXvga1

**Expected behavior**
The slider should render below the modal and not be accessible while the modal is present.

**Versions**
 - OS: Windows 7
 - Firefox Developer Edition
 - Browser Version: 63.0b14
 - Elm Version 0.19
 - Elm UI Version 1.1.0

**Workaround**
The following ellie shows how to work around the issue:

https://ellie-app.com/3DBC5vydSxxa1

It involves rendering an `Element.column` with the modal as an `Element.inFront` and rendering the slider as a `Element.row` within. The `z-index` of the modal is manually set to 20.

**Additional Research**
Removing the `z-index:10` from the `input[type=range]` reset does not work because it makes the slider non-functional in all cases.

**Comment by alexkorban** [comment]
Also happens with elm-ui 1.1.5. #bug #has-ellie

**Comment by mdgriffith** [comment]
This should be resolved with https://github.com/mdgriffith/elm-ui/commit/76701aca257299fbbea173b7bd1e9c752842131e

So, next release!
