### ISSUE TITLE
Placeholder text appears above all other elements.

### ISSUE THREAD

**Issue by dela3499** [mdgriffith/elm-ui#6]
Placeholder text appears above other things (like a semitransparent modal overlay, or dropdown menu text). Even trying to set z-indexes manually (via htmlAttribute) seems to have no effect.

https://ellie-app.com/3cMc65LsWJ4a1

**Comment by mdgriffith** [comment]
Ah, interesting.  Haven't run into z-index issues for a while.  The quick fix is to set z-index to something above 10 on the parent of the `below` element:
https://ellie-app.com/3cMnj8PjdKLa1

**Comment by dela3499** [comment]
Mysterious but effective - at least for `below`. It doesn't seem to solve the problem for `inFront` though: 
https://ellie-app.com/3cMZg2gTbJHa1

**Comment by dela3499** [comment]
Ah. Instead of raising the z-index of the modal or menu, you can just place the inputs in a container with z set to -1. 

Menu (`below`): https://ellie-app.com/3cNrkQQ7SP8a1
Modal (`inFront`): https://ellie-app.com/3cNnKwmVFyCa1

**Comment by mdgriffith** [comment]
Should be fixed by the referenced commit :)

**Comment by mdgriffith** [comment]
Basically, `below`, `above`, `onRight`, and `onLeft` will now have a higher z-index than `inFront`.  The exception being an `inFront` on `layout` as that should be in front of everyhing.
