### ISSUE TITLE
Input.text and Element.text have unexpected sizing/alignment discrepancies by default.

### ISSUE THREAD

**Issue by z5h** [mdgriffith/elm-ui#61]
`Input.text` and `Element.text`, with the same font, borders and padding applied, will be sized slightly differently.

See https://ellie-app.com/3Mk4DF8vzWZa1

Here's an example of the undesired effect:
<img width="115" alt="image" src="https://user-images.githubusercontent.com/81692/47890251-6933ee00-de24-11e8-88b1-6b4ea7175446.png">

I'd expect the two elements to have equal sizing.

The effect is noticed in Safari and Firefox on OSX.

**Comment by jhbrown94** [comment]
As of 1.1.5, I am seeing alignment differences with smaller fonts, e.g. this slight variation on @z5h's Ellie:  https://ellie-app.com/8VQDjZFCcgPa1
