### ISSUE TITLE
height fill on images

### ISSUE THREAD

**Issue by bburdette** [mdgriffith/elm-ui#62]
Here's an Ellie:
https://ellie-app.com/3MHRpp8sr2ya1

**Expected behavior**

I added the `height fill` attribute to an image, and I expected it to be shrunk to fit the available vertical area.  What actually happens is it appears at full size.  

**Versions**
 - OS: nixos
 - Browser: firefox
 - Browser Version: 62.0.3
 - Elm Version: 0.19
 - Elm UI Version 1.1.0

**Comment by HenkPoley** [comment]
The 'cool' thing is, when you change this it does work as expected 🤔:
```diff
-import Element as E exposing (column, el, row, text)
-E.layout [ E.height E.fill, Border.width 5 ] <|
+import Element as E exposing (column, el, row, text, explain)
+E.layout [ E.height E.fill, Border.width 5, explain Debug.todo ] <|
```

**Comment by HenkPoley** [comment]
With roughly these changes, you'll see that the 'explain' borders stay within the box that you want them to be (but the image/footer doesn't):

```diff
-import Element as E exposing (column, el, row, text)
-    E.layout [ E.height E.fill, Border.width 5 ] <|
+import Element as E exposing (column, el, row, text, explain)
+    E.layout [ E.height E.fill, Border.width 5, explain Debug.todo ] <|
```

**Comment by alexkorban** [comment]
Also happens with elm-ui 1.1.5. #bug #has-ellie
