### ISSUE TITLE
Some layering results are unexpected (and unresolvable).

### ISSUE THREAD

**Issue by z5h** [mdgriffith/elm-ui#69]
I'm building a typical layout where a slide-in menu on the left is displayed via 
`contentPane [inFront menuContent ]` and where menuContent is `aligntLeft`.

Content therefore, remains behind the menu.

An issue occurs if the content uses `onLeft`. This will "poke through" the menu layer.
![image](https://user-images.githubusercontent.com/81692/48563474-73dd9100-e8c2-11e8-8a4d-d95581bb0f35.png)

See example here:
https://ellie-app.com/3TtwW7LyGL4a1

This is somewhat resolvable using `behindContent` with custom translateLeft CSS:

```
translateLeft : Element.Attribute msg
translateLeft =
    Html.Attributes.style "transform" "translate(-100%)"
        |> Element.htmlAttribute
```

I'd hope that this result either wouldn't happen, or would be more easily resolvable using elm-ui primitives.

**Comment by auxsoft** [comment]
I don't know if this will be considered a bug, but the child element of the layout element could have an explicit z-order so as to create a stacking context.

In your Ellie example this can be solved by giving an explicit z-order to the contentPane.

One posibility is adding the style directly:

```
contentPane =
    Element.column
        [ 
        Element.htmlAttribute <| Html.Attributes.style "z-index" "0"
        , Element.width Element.fill
        , Element.height Element.fill
        , Background.color <| Element.rgb 1 0 0
        ]
...
```

Another way that will add a z-order to the contentPane:
```
view model =
    Element.layout
        [ 
        Element.behindContent contentPane
        , Element.inFront <|
            Element.el
                [ Element.alignLeft
                , Background.color <| Element.rgb 1 0.5 0.5
                , Element.height Element.fill
                ]
            <|
                Element.text "Side Menu .........."
        ]
        Element.none
```

**Comment by alexkorban** [comment]
Also happens with elm-ui 1.1.5. #bug #has-ellie
