### ISSUE TITLE
Input placeholder remains visible when field is not empty

### ISSUE THREAD

**Issue by PascalLeMerrer** [mdgriffith/elm-ui#71]
Here is a [simple example](https://ellie-app.com/3VQfDGRBNG7a1)

**Expected behavior**
As soon as a char is entered in the input field, the placeholder should disappear.

**Versions**
 - OS: Mac OS high Sierra
 - Browser Version:  FF63, Chrome 70
 - Elm Version: 0.19 bugfix 2
 - Elm UI Version: 1.1.0

**Comment by scottkipfer** [comment]
This is because `text` is always an empty string
You need to use the `onChange` handler to update `text`

https://ellie-app.com/48KhsB753r4a1

**Comment by alexkorban** [comment]
#unexpected

**Comment by mdgriffith** [comment]
I left a comment on #63  : https://github.com/mdgriffith/elm-ui/issues/63#issuecomment-631469931

Basically this seems like built-in virtualdom behavior as opposed to something elm-ui could adjust.  Beyond using the browser `placeholder` element, though that has limitations as well.

I'm also not sure this actually a problem. If you're using elm to handle a text input, you are going to be tracking a value in your model, yeah?

I'm going to close this for now and make a note in the docs to help people avoid it in the future.
