### ISSUE TITLE
Render bug in Chrome 41 / Google Search crawler bot

### ISSUE THREAD

**Issue by albertdahlin** [mdgriffith/elm-ui#72]
## Background

Google search indexer bot uses [Chrome 41 to render a page](https://developers.google.com/search/docs/guides/rendering) before they crawl the contents. There are several reasons for this:

- Check mobile device usability and use it as a ranking factor.
- Check page speed and use it as a ranking factor.
- Crawl SPAs or other AJAX content.
- Less importance of semantic markup. What is displayed will be crawled.
- Disable keyword stuffing or other "cheats".

This is in no way an exhaustive list but one can draw the following conclusion: How your page is
rendered can affect your ranking and/or crawlability.

## SSCCE

Since ellie-app does not work on Chrome 41 I've added the code in a [gist](https://gist.github.com/albertdahlin/45cbfd5e93c544b7d6ed20c191a623b9). You can run it in elm reactor.

I've also uploaded the compiled version on a public server for easier testing with online tools.

https://elm-ui-test.sandbox.webbhuset.com/

## Test results

To test Chrome 41 you can use [browserling.com](https://www.browserling.com/blog/779-google-chrome-41).

I have also installed Chrome 41 locally for easier testing / debugging. I will do a write up on how to do that if you find that helpful.

### Chrome 70 on Mac

This works as expected.

![image](https://user-images.githubusercontent.com/8900986/49062760-7ec6e880-f215-11e8-9819-f8547484697e.png)

### Chrome 41 on Windows 7

The elements in rows get 0 width in some cases:

![image](https://user-images.githubusercontent.com/8900986/49062724-6951be80-f215-11e8-9aec-c79bca3da374.png)

## Further Investigation

I have found that this is the rule that breaks it:

![image](https://user-images.githubusercontent.com/8900986/49063815-e599d100-f218-11e8-85c6-233964db8026.png)

When I disable that rule it in the inspector things snap back in place:

![image](https://user-images.githubusercontent.com/8900986/49063836-fd715500-f218-11e8-8cd1-938ce913925f.png)

On IE11 there is a media query override that disables that same rule which is why the page renders properly. If that override is disabled you will get the same results as in Chrome 41.

![image](https://user-images.githubusercontent.com/8900986/49063941-61941900-f219-11e8-95df-6ca6e02709d3.png)

**Versions**
 - OS: Windows, Linux and Mac
 - Browser: Chrome
 - Browser: 41
 - Elm: 0.19
 - Elm UI Version: 1.1.0

**Comment by albertdahlin** [comment]
I used these steps to install Chrome 41 locally on my Mac

Download the binary:
https://google-chrome.en.uptodown.com/mac/download/113085

Follow these instructions
https://zhoukekestar.github.io/notes/2017/11/01/install-multi-chrome.html

**Comment by mdgriffith** [comment]
Awesome research.

I think we're ok now, it' looks like Google's webcrawler now uses the evergreen version of chrome:
https://searchengineland.com/google-will-ensure-googlebot-runs-the-latest-version-of-chromium-316534

Seriously though, awesome research, complete with examples and everything. Love it.

**Comment by albertdahlin** [comment]
Yup, I can confirm that this is no longer a problem. Thanks for the awesome work with Elm UI (and other packages).
