### ISSUE TITLE
'width' with a 'minimum' or 'maximum' doesn't cancel out another 'width' with a 'maximum' or 'minimum' set.

### ISSUE THREAD

**Issue by danabrams** [mdgriffith/elm-ui#77]
`width` with a `minimum` or `maximum` doesn’t cancel out a other `width` with a `maximum` or `minimum` set.

Doesn't seem to effect absolute 'widths'.

Solving may also solve issue #42 .

**Comment by mdgriffith** [comment]
Thanks man!  finally fixed it.
