### ISSUE TITLE
[Feature Request] Support for multiple shadow parts (ex: umbra, penumbra, antumbra)

### ISSUE THREAD

**Issue by rlefevre** [mdgriffith/elm-ui#98]
CSS shadows can better approximate the real world physics by using several parts: umbra, penumbra and antumbra:

https://en.wikipedia.org/wiki/Umbra,_penumbra_and_antumbra

For example, some material design implementations use umbra, penumbra and ambient parts:
https://github.com/material-components/material-components-web/blob/e02b4c9fa2bd026c695f3a71efce58d01f460269/packages/mdc-elevation/_variables.scss

Currently, with `elm-ui 1.1.0`, `Border.shadow` only supports one shadow part.

Please consider adding support for multiple parts to improve the design of shadows.

Also see https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#Interpolation for the interpolation rules.

**Comment by mdgriffith** [comment]
Awesome references!  I'll definitely look into this.

**Comment by AlienKevin** [comment]
I second that. Some new cool designs use multiple shadows on a single element. For instance, [Neumorphism](https://neumorphism.io/#55b9f3) uses a light and a dark shadow. Multiple shadow parts will make the implementation of these designs much easier in elm-ui.

**Comment by dullbananas** [comment]
im trying to use this for neumorphism

**Comment by dullbananas** [comment]
@mdgriffith im still waiting for this feature
