### ISSUE TITLE
Can't align right in table cell

### ISSUE THREAD

**Issue by skyqrose** [mdgriffith/elm-ui#99]
`Element.alignRight` does not work when a direct child of a table cell, so aligning right inside a table requires an extra `Element.el` layer.

Expected: you could align right directly inside a table cell.

I ran into this when trying to align right numerical data, which I assume is a common case when using tables.

[SSCCE in Ellie](https://ellie-app.com/57Lzm3zycd2a1)
```
    El.layout []
        ( El.table
            []
            { data =
                [ El.el
                    [ El.alignRight ]
                    (El.text "one el")
                , El.el [] <|
                    El.el
                        [ El.alignRight ]
                        (El.text "nested")
                ]
              , columns =
                  [ { header = El.none
                    , width = El.fill
                    , view = identity
                    }
                  ]
              }
          )
```

![Screenshot from 2019-03-30 22-25-49](https://user-images.githubusercontent.com/23065557/55283941-cfbd2980-533a-11e9-8f03-f91bc7c1129e.png)

**Versions**
 - OS: Fedora 29
 - Browser: Firefox 66
 - Elm Version 0.19
 - Elm UI Version 1.1.0

I have not tried this on other browsers or versions. I have not checked if there are any attributes other than `alignRight` that don't behave properly.

**Comment by roberto** [comment]
Hi, @skyqrose !

Have you tried to use `Font.alignRight` ?
https://ellie-app.com/5qZjpmCsW7va1

**Comment by skyqrose** [comment]
Ah, I didn't realize that there was a separate `alignRight` for moving text vs elements. That worked.

Given that this library is meant to reduce "gotcha"s, should they be combined? Or is aligning text a fundamentally different idea than aligning elements.

Perhaps the documentation should add a note to reduce surprises. "If you're aligning the other type of thing, use [Font.alignRight](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element-Font#alignRight) instead."

My problme's been solved, so if there's nothing actionable out this issue, feel free to close it.

**Comment by roberto** [comment]
> Perhaps the documentation should add a note to reduce surprises. "If you're aligning the other type of thing, use [Font.alignRight](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element-Font#alignRight) instead."

@skyqrose I totally agree with you. So, I've created a PR adding a note about this: #105. Please, review! :)

**Comment by Maxim-Filimonov** [comment]
I believe, it's actually a bug.
See this ellie for example:
https://ellie-app.com/5sy4pwmJfsSa1

There is inconsistency in how `el [centerX]` behaves depending if it's within a table or not.
